"use client"

import './globals.css'
import { Inter } from 'next/font/google';
import Container from "react-bootstrap/Container";
import Head from "next/head";



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="pt-br">
            <Head>
                <title>Bootstrap w/ React</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <body className='body'>
                <Container>
                    {children}
                </Container>
            </body>
        </html>
    )
}
